### ISSUE TITLE
Demos contain a lot of extraneous libraries

### ISSUE THREAD

**Issue by curelom** [kevicency/CMContrib#1]
Could we remove all the extra libraries in the demos?  It makes it difficult to run them and follow them trying to get all the libraries installed.  I still don't know where to get WPF.Themes and ColorCode from.

**Comment by kevicency** [comment]
Hey, did you run the "update_packages.ps1" script in the project root? it should fetch all required libraries through NuGet

**Comment by curelom** [comment]
Ok, the problem turned out to be that the extended wpf toolkit had changed their namespace to Xceed.Wpf.Toolkit
